### PR TITLE
Update some meta data

### PR DESCRIPTION
**Pull request by ukmadlz**

### CODE REVIEW

**Comment by jakeydevs** [comment]
+1

**Comment by curtis-h** [comment]
"Curt Harding"...really? :-P

**Comment by ukmadlz** [comment]
You want your full name?

**Comment by curtis-h** [comment]
I'd prefer "Curtis Harding" yea.

**Comment by ukmadlz** [comment]
Done, if you're happy with it now just merge it from gh

**Comment by curtis-h** [comment]
Cheers, merging

**Pull request merged**
